data _null_;
file pyfl encoding='utf-8';
put 'import csv';
put 'import sys';
put 'def f3(filename):';
put '   with open(filename, "rb") as csvfile:';
put '       csvreader = csv.reader(csvfile, delimiter=";")';
put '       while (True):';
put '           row = [unicode("Error", "utf-8")]';
put '           try:';
put '               line = csvreader.next()';
put '               try:';
put '                   row = [unicode(cell, "cp1251") for cell in line]';
put '               except UnicodeDecodeError:';
put '                   try:';
put '                       row = [unicode(cell, "utf-8") for cell in line]';
put '                   except UnicodeDecodeError as e:';
put '                       raise e';
put '           except StopIteration:';
put '               break';
put '           except :';
put '               pass';
put '           yield row';
put 'if __name__ == "__main__":';
put '   if len(sys.argv) < 2:';
put '       print("Insufficient number of arguments")';
put '       print("Use python {0} filename_to_read".format(sys.argv[0]))';
put '       sys.exit(1)';
put '   for item in f3(sys.argv[1]):';
put '       print("\t".join(map(lambda el: el.encode("utf-8").replace("\r\n", ""), item)))';
run;

filename qweasd pipe "python %sysfunc(pathname(pyfl)) /path/to/class.csv";

data WORK.RESULT;
if 0 then set SASHELP.CLASS;
infile qweasd encoding='utf-8' dsd dlm="09"x truncover ;
input %varlist(SASHELP.CLASS);
%do_quotechar(SASHELP.CLASS);
run;